"""initial schema

Revision ID: 1f5da3232211
Revises:
Create Date: 2026-09-04 18:48:09.812028

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f5da3232211'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# All native PostgreSQL ENUM types are declared once here with
# create_type=False and created/dropped explicitly in upgrade()/downgrade()
# below, rather than relying on the (unreliable, and outright broken for
# types shared across >1 table) implicit create-on-first-use /
# drop-on-table-drop behavior that op.create_table()/op.drop_table() give a
# plain inline sa.Enum(...). This keeps upgrade -> downgrade -> upgrade
# fully deterministic.
user_role_enum = postgresql.ENUM(
    'admin', 'legal_ops', 'viewer', name='user_role', create_type=False
)
contract_type_enum = postgresql.ENUM(
    'NDA', 'MSA', 'Lease', 'License', 'Employment', 'Vendor', 'Other',
    name='contract_type', create_type=False,
)
contract_status_enum = postgresql.ENUM(
    'processing', 'needs_review', 'active', 'expired', 'terminated', 'error',
    name='contract_status', create_type=False,
)
obligation_category_enum = postgresql.ENUM(
    'RENEWAL', 'TERMINATION_NOTICE', 'PAYMENT_MILESTONE', 'SLA_COMMITMENT',
    'INDEMNIFICATION', 'CONFIDENTIALITY', 'NON_COMPETE', 'LIMITATION_OF_LIABILITY',
    'GOVERNING_LAW', 'AUDIT_RIGHTS', 'DATA_PROTECTION', 'OTHER_OBLIGATION',
    name='obligation_category', create_type=False,
)
recurrence_type_enum = postgresql.ENUM(
    'none', 'monthly', 'quarterly', 'annually', name='recurrence_type', create_type=False
)
obligation_status_enum = postgresql.ENUM(
    'upcoming', 'at_risk', 'overdue', 'resolved', 'waived',
    name='obligation_status', create_type=False,
)
alert_type_enum = postgresql.ENUM('email', 'in_app', name='alert_type', create_type=False)
alert_status_enum = postgresql.ENUM(
    'pending', 'sent', 'failed', 'cancelled', name='alert_status', create_type=False
)
extraction_job_status_enum = postgresql.ENUM(
    'queued', 'running', 'succeeded', 'failed',
    name='extraction_job_status', create_type=False,
)
llm_provider_name_enum = postgresql.ENUM(
    'groq', 'gemini', name='llm_provider_name', create_type=False
)

ALL_ENUMS = (
    user_role_enum,
    contract_type_enum,
    contract_status_enum,
    obligation_category_enum,
    recurrence_type_enum,
    obligation_status_enum,
    alert_type_enum,
    alert_status_enum,
    extraction_job_status_enum,
    llm_provider_name_enum,
)


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any table can declare a vector(...) column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_log',
    sa.Column('provider', llm_provider_name_enum, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'date', name='uq_llm_usage_log_provider_date')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clause_precedent_cache',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('category', obligation_category_enum, nullable=False),
    sa.Column('cached_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clause_precedent_cache_embedding_hnsw', 'clause_precedent_cache', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_clause_precedent_cache_org_id'), 'clause_precedent_cache', ['org_id'], unique=False)
    op.create_index(op.f('ix_clause_precedent_cache_text_hash'), 'clause_precedent_cache', ['text_hash'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('contracts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('counterparty_name', sa.String(length=500), nullable=True),
    sa.Column('contract_type', contract_type_enum, nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', contract_status_enum, nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('original_expiration_date', sa.Date(), nullable=True),
    sa.Column('governing_law', sa.String(length=255), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_file_hash'), 'contracts', ['file_hash'], unique=False)
    op.create_index(op.f('ix_contracts_org_id'), 'contracts', ['org_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('contract_chunks',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('is_boilerplate', sa.Boolean(), nullable=False),
    sa.Column('passed_prefilter', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_chunks_contract_id'), 'contract_chunks', ['contract_id'], unique=False)
    op.create_index('ix_contract_chunks_embedding_hnsw', 'contract_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('extraction_jobs',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('status', extraction_job_status_enum, nullable=False),
    sa.Column('llm_provider_used', llm_provider_name_enum, nullable=True),
    sa.Column('tokens_used_estimate', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_contract_id'), 'extraction_jobs', ['contract_id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_status'), 'extraction_jobs', ['status'], unique=False)
    op.create_table('obligations',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('category', obligation_category_enum, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible_party', sa.String(length=500), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('computed_alert_date', sa.Date(), nullable=True),
    sa.Column('monetary_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('recurrence', recurrence_type_enum, nullable=False),
    sa.Column('status', obligation_status_enum, nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_human_reviewed', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('raw_source_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['contract_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_category'), 'obligations', ['category'], unique=False)
    op.create_index(op.f('ix_obligations_computed_alert_date'), 'obligations', ['computed_alert_date'], unique=False)
    op.create_index(op.f('ix_obligations_contract_id'), 'obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_trigger_date'), 'obligations', ['trigger_date'], unique=False)
    op.create_table('alerts',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', alert_type_enum, nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', alert_status_enum, nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_obligation_id'), 'alerts', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_obligation_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_obligations_trigger_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_contract_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_computed_alert_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_category'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_extraction_jobs_status'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_contract_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index('ix_contract_chunks_embedding_hnsw', table_name='contract_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_contract_chunks_contract_id'), table_name='contract_chunks')
    op.drop_table('contract_chunks')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_org_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_file_hash'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clause_precedent_cache_text_hash'), table_name='clause_precedent_cache')
    op.drop_index(op.f('ix_clause_precedent_cache_org_id'), table_name='clause_precedent_cache')
    op.drop_index('ix_clause_precedent_cache_embedding_hnsw', table_name='clause_precedent_cache', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('clause_precedent_cache')
    op.drop_table('organizations')
    op.drop_table('llm_usage_log')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.drop(bind, checkfirst=True)
