/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_v1_admin_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/alerts/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Alert Scan
         * @description Runs the same daily recompute-status + send-alerts job the `worker`
         *     process runs on its cron schedule, on demand — for testing/demoing
         *     without waiting a day (docs/CONTRACT_CLM_BUILD_PLAN.md §12 Phase 7).
         *     Scans the whole platform, not just this admin's org, matching the
         *     worker's own scope.
         */
        post: operations["trigger_alert_scan_api_v1_admin_alerts_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/extraction/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Extraction Retry
         * @description Re-attempts every extraction_job still QUEUED — left that way when no
         *     LLM provider had quota headroom at upload time. Runs on the worker's own
         *     schedule too (see worker.py); this endpoint exists for the same
         *     on-demand testing/demoing reason as /admin/alerts/scan. Scans the whole
         *     platform, not just this admin's org, matching that endpoint's scope.
         */
        post: operations["trigger_extraction_retry_api_v1_admin_extraction_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/llm-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Usage
         * @description Today's Groq/Gemini quota usage, for ops visibility
         *     (docs/CONTRACT_CLM_BUILD_PLAN.md §8). Usage is platform-wide, not
         *     per-org — quota is consumed against one shared set of provider API
         *     keys, not allocated per tenant.
         */
        get: operations["get_llm_usage_api_v1_admin_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_api_v1_contracts_get"];
        put?: never;
        /** Upload Contract */
        post: operations["upload_contract_api_v1_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_api_v1_contracts__contract_id__get"];
        put?: never;
        post?: never;
        /** Delete Contract */
        delete: operations["delete_contract_api_v1_contracts__contract_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{contract_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract File
         * @description Streams the original uploaded file back — e.g. for the frontend's
         *     inline PDF viewer. `storage_path` is always server-generated
         *     (`{org_id}/{contract_id}.{ext}`, never derived from user input — see
         *     services/storage.py), so this is safe from path traversal.
         */
        get: operations["get_contract_file_api_v1_contracts__contract_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{contract_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract Status */
        get: operations["get_contract_status_api_v1_contracts__contract_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Obligations */
        get: operations["list_obligations_api_v1_obligations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/obligations/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Obligation Calendar
         * @description Everything still actionable that's due within the window, plus
         *     anything already overdue — the data behind the "expiring in 30/60/90
         *     days" dashboard view (docs/CONTRACT_CLM_BUILD_PLAN.md §8).
         */
        get: operations["get_obligation_calendar_api_v1_obligations_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/obligations/{obligation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Obligation */
        get: operations["get_obligation_api_v1_obligations__obligation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Obligation */
        patch: operations["update_obligation_api_v1_obligations__obligation_id__patch"];
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Dismiss Alert */
        patch: operations["dismiss_alert_api_v1_alerts__alert_id__dismiss_patch"];
        trace?: never;
    };
    "/api/v1/precedents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Precedents */
        get: operations["search_precedents_api_v1_precedents_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_api_v1_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_chat_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feedback */
        patch: operations["update_feedback_api_v1_chat_messages__message_id__feedback_patch"];
        trace?: never;
    };
    "/api/v1/chat/admin/evaluation-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Summary */
        get: operations["get_evaluation_summary_api_v1_chat_admin_evaluation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertScanResponse */
        AlertScanResponse: {
            /** Statuses Recomputed */
            statuses_recomputed: number;
            /** Alerts Sent */
            alerts_sent: number;
            /** Alerts Failed */
            alerts_failed: number;
            /** Alerts Skipped Duplicate */
            alerts_skipped_duplicate: number;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "pending" | "sent" | "failed" | "cancelled";
        /** AlertSummary */
        AlertSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Obligation Id
             * Format: uuid
             */
            obligation_id: string;
            alert_type: components["schemas"]["AlertType"];
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["AlertStatus"];
            /**
             * Recipient User Id
             * Format: uuid
             */
            recipient_user_id: string;
        };
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "email" | "in_app";
        /**
         * AnswerDiagnostics
         * @description The full "why did the pipeline answer this way" trail for one
         *     turn — persisted on the assistant ChatMessage (and streamed in the
         *     SSE `done` event) only when confidence="insufficient_information", so
         *     a user who gets declined can see what was actually retrieved and
         *     which guardrail or threshold turned it away, rather than just the
         *     fixed apology string.
         */
        AnswerDiagnostics: {
            /** Decision Reason */
            decision_reason: ("no_candidates_found" | "below_relevance_threshold" | "llm_unavailable" | "llm_self_declined" | "legal_advice_framing" | "uncited_claim" | "failed_faithfulness_check") | "answered";
            /** Relevance Threshold */
            relevance_threshold: number;
            /** Attempts */
            attempts: components["schemas"]["RetrievalAttempt"][];
        };
        /**
         * AuditLogEntry
         * @description Built field-by-field in the endpoint rather than via
         *     `model_validate(..., from_attributes=True)`: the ORM attribute is
         *     `AuditLog.metadata_` (`metadata` is reserved by SQLAlchemy's
         *     declarative base), so an automatic from-attributes mapping of a field
         *     literally named `metadata` would silently read the wrong thing.
         */
        AuditLogEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_contract_api_v1_contracts_post */
        Body_upload_contract_api_v1_contracts_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
            /** @default Other */
            contract_type: components["schemas"]["ContractType"];
        };
        /** CalendarEntry */
        CalendarEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Contract Title */
            contract_title: string;
            category: components["schemas"]["ObligationCategory"];
            /** Description */
            description: string;
            /** Responsible Party */
            responsible_party: string | null;
            /** Trigger Date */
            trigger_date: string | null;
            /** Notice Period Days */
            notice_period_days: number | null;
            /** Computed Alert Date */
            computed_alert_date: string | null;
            /** Monetary Amount */
            monetary_amount: number | null;
            /** Currency */
            currency: string | null;
            recurrence: components["schemas"]["RecurrenceType"];
            status: components["schemas"]["ObligationStatus"];
            /** Confidence Score */
            confidence_score: number | null;
            /** Is Human Reviewed */
            is_human_reviewed: boolean;
            /** Assigned To */
            assigned_to: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChatCitation
         * @description One numbered reference in an assistant answer, per plan §4 —
         *     `ref_number` matches an inline `[n]` marker in `answer_text`.
         *
         *     `source_chunk_id`/`contract_id` are null for a clause-benchmark
         *     citation into the CUAD reference corpus (plan §3.2): that material
         *     isn't one of the requesting org's own contracts, so there's no
         *     document-viewer page for the frontend's "View in document" action to
         *     open — the citation is still real and shown, just not clickable.
         *     `is_reference_corpus` is what the frontend uses to tell the two apart
         *     without inferring it from a null check.
         */
        ChatCitation: {
            /** Ref Number */
            ref_number: number;
            /** Source Chunk Id */
            source_chunk_id: string | null;
            /** Contract Id */
            contract_id: string | null;
            /** Contract Title */
            contract_title: string;
            /** Snippet */
            snippet: string;
            /**
             * Is Reference Corpus
             * @default false
             */
            is_reference_corpus: boolean;
        };
        /**
         * ChatConfidence
         * @enum {string}
         */
        ChatConfidence: "high" | "medium" | "low" | "insufficient_information";
        /**
         * ChatFeedback
         * @enum {string}
         */
        ChatFeedback: "none" | "up" | "down";
        /** ChatFeedbackUpdate */
        ChatFeedbackUpdate: {
            feedback: components["schemas"]["ChatFeedback"];
        };
        /**
         * ChatIntent
         * @enum {string}
         */
        ChatIntent: "domain_question" | "clause_benchmark" | "calendar_query" | "out_of_scope";
        /** ChatMessageCreate */
        ChatMessageCreate: {
            /** Content */
            content: string;
        };
        /** ChatMessageSummary */
        ChatMessageSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["ChatRole"];
            /** Content */
            content: string;
            confidence: components["schemas"]["ChatConfidence"] | null;
            intent: components["schemas"]["ChatIntent"] | null;
            /** Citations */
            citations: components["schemas"]["ChatCitation"][] | null;
            feedback: components["schemas"]["ChatFeedback"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            retrieval_diagnostics?: components["schemas"]["AnswerDiagnostics"] | null;
        };
        /**
         * ChatRole
         * @enum {string}
         */
        ChatRole: "user" | "assistant" | "system";
        /** ChatSessionCreate */
        ChatSessionCreate: {
            scope: components["schemas"]["ChatSessionScope"];
            /** Contract Id */
            contract_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** ChatSessionDetail */
        ChatSessionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            scope: components["schemas"]["ChatSessionScope"];
            /** Contract Id */
            contract_id: string | null;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessageSummary"][];
        };
        /**
         * ChatSessionScope
         * @enum {string}
         */
        ChatSessionScope: "organization" | "contract";
        /** ChatSessionSummary */
        ChatSessionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            scope: components["schemas"]["ChatSessionScope"];
            /** Contract Id */
            contract_id: string | null;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContractDetail */
        ContractDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Counterparty Name */
            counterparty_name: string | null;
            contract_type: components["schemas"]["ContractType"];
            status: components["schemas"]["ContractStatus"];
            /** Effective Date */
            effective_date: string | null;
            /** Original Expiration Date */
            original_expiration_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Original Filename */
            original_filename: string;
            /** Governing Law */
            governing_law: string | null;
            /** Contract Value */
            contract_value: number | null;
            /** Currency */
            currency: string | null;
            /** Extraction Confidence */
            extraction_confidence: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContractStatus
         * @enum {string}
         */
        ContractStatus: "processing" | "needs_review" | "active" | "expired" | "terminated" | "error";
        /** ContractStatusResponse */
        ContractStatusResponse: {
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            contract_status: components["schemas"]["ContractStatus"];
            latest_extraction_job: components["schemas"]["ExtractionJobSummary"] | null;
        };
        /** ContractSummary */
        ContractSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Counterparty Name */
            counterparty_name: string | null;
            contract_type: components["schemas"]["ContractType"];
            status: components["schemas"]["ContractStatus"];
            /** Effective Date */
            effective_date: string | null;
            /** Original Expiration Date */
            original_expiration_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ContractType
         * @enum {string}
         */
        ContractType: "NDA" | "MSA" | "Lease" | "License" | "Employment" | "Vendor" | "Other";
        /** ContractUploadResponse */
        ContractUploadResponse: {
            contract: components["schemas"]["ContractDetail"];
            /**
             * Extraction Job Id
             * Format: uuid
             */
            extraction_job_id: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** At Risk Count */
            at_risk_count: number;
            /** Overdue Count */
            overdue_count: number;
            /** Upcoming This Month Count */
            upcoming_this_month_count: number;
            /** Total Active Contract Value */
            total_active_contract_value: {
                [key: string]: number;
            };
        };
        /**
         * EvaluationSummary
         * @description Plan §7's admin quality view: online signal (real user feedback,
         *     always available) plus offline signal (the last CI-gated RAGAS-style
         *     run, when scripts/run_rag_evaluation.py has been run at least once —
         *     see docs/CHATBOT_EVALUATION.md). `offline_*` fields are null rather
         *     than fabricated when no evaluation run has ever been recorded.
         */
        EvaluationSummary: {
            /** Total Assistant Messages */
            total_assistant_messages: number;
            /** Feedback Up Count */
            feedback_up_count: number;
            /** Feedback Down Count */
            feedback_down_count: number;
            /** Insufficient Information Rate */
            insufficient_information_rate: number;
            /** Offline Eval Run At */
            offline_eval_run_at: string | null;
            /** Offline Faithfulness */
            offline_faithfulness: number | null;
            /** Offline Answer Relevancy */
            offline_answer_relevancy: number | null;
            /** Offline Context Precision */
            offline_context_precision: number | null;
            /** Offline Context Recall */
            offline_context_recall: number | null;
        };
        /**
         * ExtractionJobStatus
         * @enum {string}
         */
        ExtractionJobStatus: "queued" | "running" | "succeeded" | "failed";
        /** ExtractionJobSummary */
        ExtractionJobSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ExtractionJobStatus"];
            llm_provider_used: components["schemas"]["LLMProviderName"] | null;
            /** Tokens Used Estimate */
            tokens_used_estimate: number | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /** ExtractionRetryResponse */
        ExtractionRetryResponse: {
            /** Jobs Retried */
            jobs_retried: number;
            /** Jobs Succeeded */
            jobs_succeeded: number;
            /** Jobs Still Queued */
            jobs_still_queued: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App Name */
            app_name: string;
            /** Environment */
            environment: string;
        };
        /**
         * LLMProviderName
         * @enum {string}
         */
        LLMProviderName: "groq" | "gemini";
        /** LLMUsageSummary */
        LLMUsageSummary: {
            provider: components["schemas"]["LLMProviderName"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Requests Used */
            requests_used: number;
            /** Tokens Used */
            tokens_used: number;
            /** Requests Limit */
            requests_limit: number;
            /** Tokens Limit */
            tokens_limit: number;
            /** Has Headroom */
            has_headroom: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ObligationCategory
         * @enum {string}
         */
        ObligationCategory: "RENEWAL" | "TERMINATION_NOTICE" | "PAYMENT_MILESTONE" | "SLA_COMMITMENT" | "INDEMNIFICATION" | "CONFIDENTIALITY" | "NON_COMPETE" | "LIMITATION_OF_LIABILITY" | "GOVERNING_LAW" | "AUDIT_RIGHTS" | "DATA_PROTECTION" | "OTHER_OBLIGATION";
        /** ObligationDetail */
        ObligationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Contract Title */
            contract_title: string;
            category: components["schemas"]["ObligationCategory"];
            /** Description */
            description: string;
            /** Responsible Party */
            responsible_party: string | null;
            /** Trigger Date */
            trigger_date: string | null;
            /** Notice Period Days */
            notice_period_days: number | null;
            /** Computed Alert Date */
            computed_alert_date: string | null;
            /** Monetary Amount */
            monetary_amount: number | null;
            /** Currency */
            currency: string | null;
            recurrence: components["schemas"]["RecurrenceType"];
            status: components["schemas"]["ObligationStatus"];
            /** Confidence Score */
            confidence_score: number | null;
            /** Is Human Reviewed */
            is_human_reviewed: boolean;
            /** Assigned To */
            assigned_to: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Source Chunk Id */
            source_chunk_id: string | null;
            /** Raw Source Text */
            raw_source_text: string | null;
        };
        /**
         * ObligationStatus
         * @enum {string}
         */
        ObligationStatus: "upcoming" | "at_risk" | "overdue" | "resolved" | "waived";
        /** ObligationSummary */
        ObligationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Contract Title */
            contract_title: string;
            category: components["schemas"]["ObligationCategory"];
            /** Description */
            description: string;
            /** Responsible Party */
            responsible_party: string | null;
            /** Trigger Date */
            trigger_date: string | null;
            /** Notice Period Days */
            notice_period_days: number | null;
            /** Computed Alert Date */
            computed_alert_date: string | null;
            /** Monetary Amount */
            monetary_amount: number | null;
            /** Currency */
            currency: string | null;
            recurrence: components["schemas"]["RecurrenceType"];
            status: components["schemas"]["ObligationStatus"];
            /** Confidence Score */
            confidence_score: number | null;
            /** Is Human Reviewed */
            is_human_reviewed: boolean;
            /** Assigned To */
            assigned_to: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ObligationUpdate
         * @description PATCH body covering every human-review action from
         *     docs/CONTRACT_CLM_BUILD_PLAN.md §8 (edit/confirm/waive) as one endpoint:
         *     an empty body just confirms the extraction as-is; setting `status` to
         *     `waived` (or any other value) records that decision explicitly;
         *     setting any other field corrects the extracted data. Only fields the
         *     caller actually sends are applied — see api/v1/obligations.py's use of
         *     `exclude_unset=True`. Calling this endpoint at all marks the obligation
         *     human-reviewed, since only editor/admin roles can reach it.
         */
        ObligationUpdate: {
            category?: components["schemas"]["ObligationCategory"] | null;
            /** Description */
            description?: string | null;
            /** Responsible Party */
            responsible_party?: string | null;
            /** Trigger Date */
            trigger_date?: string | null;
            /** Notice Period Days */
            notice_period_days?: number | null;
            /** Monetary Amount */
            monetary_amount?: number | null;
            /** Currency */
            currency?: string | null;
            recurrence?: components["schemas"]["RecurrenceType"] | null;
            status?: components["schemas"]["ObligationStatus"] | null;
            /** Assigned To */
            assigned_to?: string | null;
        };
        /** PrecedentSearchResult */
        PrecedentSearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Contract Title */
            contract_title: string;
            /** Section Heading */
            section_heading: string | null;
            /** Raw Text */
            raw_text: string;
            /** Similarity */
            similarity: number;
        };
        /**
         * RankedCandidate
         * @description One reranked chunk from a retrieval attempt, kept regardless of
         *     whether it cleared `chat_min_relevance_threshold` — this is what
         *     powers the "here's what we found and why it wasn't used" panel on an
         *     insufficient_information answer. `score` is the same post-sigmoid
         *     [0,1] cross-encoder score the threshold itself is compared against.
         */
        RankedCandidate: {
            /** Contract Title */
            contract_title: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
            /** Passed Threshold */
            passed_threshold: boolean;
            /**
             * Is Reference Corpus
             * @default false
             */
            is_reference_corpus: boolean;
        };
        /**
         * RecurrenceType
         * @enum {string}
         */
        RecurrenceType: "none" | "monthly" | "quarterly" | "annually";
        /** RegisterRequest */
        RegisterRequest: {
            /** Org Name */
            org_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * RetrievalAttempt
         * @description One call into `_retrieve_reference_items` (pipeline.py). An
         *     org-wide question naming a contract by title makes two attempts —
         *     "narrowed" first, "unrestricted" only if that came back empty — a
         *     contract-scoped session or an unnamed question makes exactly one,
         *     "unrestricted".
         */
        RetrievalAttempt: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "narrowed" | "unrestricted";
            /** Narrowed To Contract Count */
            narrowed_to_contract_count: number;
            /** Top Candidates */
            top_candidates: components["schemas"]["RankedCandidate"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "legal_ops" | "viewer";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    ping_api_v1_admin_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    trigger_alert_scan_api_v1_admin_alerts_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertScanResponse"];
                };
            };
        };
    };
    trigger_extraction_retry_api_v1_admin_extraction_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRetryResponse"];
                };
            };
        };
    };
    get_llm_usage_api_v1_admin_llm_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMUsageSummary"][];
                };
            };
        };
    };
    list_contracts_api_v1_contracts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ContractStatus"] | null;
                contract_type?: components["schemas"]["ContractType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_contract_api_v1_contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_contract_api_v1_contracts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_api_v1_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contract_api_v1_contracts__contract_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_file_api_v1_contracts__contract_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_status_api_v1_contracts__contract_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_obligations_api_v1_obligations_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["ObligationCategory"] | null;
                status?: components["schemas"]["ObligationStatus"] | null;
                contract_id?: string | null;
                assigned_to?: string | null;
                trigger_date_from?: string | null;
                trigger_date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_obligation_calendar_api_v1_obligations_calendar_get: {
        parameters: {
            query?: {
                within_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_obligation_api_v1_obligations__obligation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_obligation_api_v1_obligations__obligation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObligationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_alert_api_v1_alerts__alert_id__dismiss_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_precedents_api_v1_precedents_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecedentSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_api_v1_audit_log_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSummary"][];
                };
            };
        };
    };
    create_session_api_v1_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_chat_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feedback_api_v1_chat_messages__message_id__feedback_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatFeedbackUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_summary_api_v1_chat_admin_evaluation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummary"];
                };
            };
        };
    };
}
